{"name": "test_1", "status": "skipped", "statusDetails": {"message": "AssertionError: assert False", "trace": "@pytest.mark.xfail(True,reason=\"\")\n    def test_1():\n        print(\"预期失败,结果失败\")\n>       assert False\nE       assert False\n\nscript\\test_xafil.py:17: AssertionError"}, "start": 1574227812329, "stop": 1574227812330, "uuid": "e06723a0-8216-4ae5-a492-96f07496e6d6", "historyId": "7e65e8e8636e5ba324f5d38ccbe1a2bb", "testCaseId": "9bd596cb33732bf1284790d5eea24c98", "fullName": "script.test_xafil#test_1", "labels": [{"name": "parentSuite", "value": "script"}, {"name": "suite", "value": "test_xafil"}, {"name": "host", "value": "DESKTOP-E0IFP26"}, {"name": "thread", "value": "13012-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "script.test_xafil"}]}