{"name": "test_3", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "@pytest.mark.xfail(False,reason=\"\")\n    def test_3():\n        print(\"预期成功,结果失败\")\n>       assert False\nE       assert False\n\nscript\\test_xafil.py:26: AssertionError"}, "start": 1574227812356, "stop": 1574227812356, "uuid": "a5640389-2fc7-498c-9310-af0e9d8001c9", "historyId": "68c66588e220eebed3843255e86c303b", "testCaseId": "c4e3871b5a1c8a0258cf2f4e959ff222", "fullName": "script.test_xafil#test_3", "labels": [{"name": "parentSuite", "value": "script"}, {"name": "suite", "value": "test_xafil"}, {"name": "host", "value": "DESKTOP-E0IFP26"}, {"name": "thread", "value": "13012-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "script.test_xafil"}]}